force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <label>Deal</label>
    <nameField>
        <displayFormat>DL-{0000}</displayFormat>
        <label>Deal ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Deal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deal__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DealTriggerHandler.cls
public class DealTriggerHandler {
    public static void preventDealGeneration(List<Deal__c> dealRecord){
        Set<Id> vehicleSet = new Set<Id>();
    	for(Deal__c deal: dealRecord){
        	if(deal.Vehicle__c != Null){
     			vehicleSet.add(deal.Vehicle__c);
    		}
    	}
     	Map<Id,Vehicle__c> vehicleMap = new Map<Id,Vehicle__c>([Select Id,Inventory__c from Vehicle__c where Id IN :vehicleSet]);
        for(Deal__c deal: dealRecord){
            Vehicle__c dealVehicle = vehicleMap.get(deal.Vehicle__c);
        	if(dealVehicle.Inventory__c == 0 || dealVehicle.Inventory__c == Null){
            	deal.addError('Insufficient inventory count for the requested deal.');
        	}
    	}
    }
    public static void updateInventory(List<Deal__c> dealRecord, Map<Id,Deal__c> oldMap){
		Set<Id> vehicleSet = new Set<Id>();
    	for(Deal__c deal: dealRecord){
        	if(deal.Vehicle__c != Null){
     			vehicleSet.add(deal.Vehicle__c);
    		}
    	}
     	Map<Id,Vehicle__c> vehicleMap = new Map<Id,Vehicle__c>([Select Id,Inventory__c from Vehicle__c where Id IN :vehicleSet]);
        List<Vehicle__c> updatedVehicles = new List<Vehicle__c>();
        for(Deal__c deal : dealRecord ){
            if(deal.Status__c != oldMap.get(deal.Id).Status__c && deal.Status__c == 'Approved'){
					Vehicle__c dealVehicle = vehicleMap.get(deal.Vehicle__c);
					dealVehicle.Inventory__c -= 1;    
                	updatedVehicles.add(dealVehicle);
            }
        }
        if(!updatedVehicles.isEmpty()){
       		update updatedVehicles;
        }
    }
}